---
title: "Network_test_SUB"
author: "Nat Pombubpa"
date: "5/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(phyloseq)
library(SpiecEasi)
library(RCy3)
library(igraph)
library(ggplot2)
library(plyr)
```

###SpiecEasi Test

####Bacteria
```{r warning=FALSE}
Bac.otus <- read.table("MC2018.network.BAC.otu_table.csv",
                   header=T,sep=",",row.names = 1)
Bac.otumat <- as(as.matrix(Bac.otus), "matrix")
Bac.OTU = otu_table(Bac.otumat, taxa_are_rows = TRUE)
```

```{r}
Bac.taxmat <- read.table("BAC.network.taxonomy.csv", header=T,sep=",",row.names=1)
Bac.taxmat <- as(as.matrix(Bac.taxmat),"matrix")
Bac.TAX = tax_table(Bac.taxmat)
```

```{r warning=FALSE}
meta = read.table("Mojave_mappingfile_8-Aug-2018.txt",
                  header=TRUE,row.names=1,
                  sep="\t",stringsAsFactors=FALSE)
```

```{r warning=FALSE}
sampleData <- sample_data(meta)
```

```{r warning=FALSE}
Bac.physeq = phyloseq(Bac.OTU,Bac.TAX,sampleData)
```

```{r}
Bac.physeq.prune = prune_taxa(taxa_sums(Bac.physeq) > 5, Bac.physeq)
```

```{r warning=FALSE}
set.seed(711)
Bac.physeq.prune.rarefy = rarefy_even_depth(Bac.physeq.prune, sample.size = 37435, replace = FALSE, trimOTUs = TRUE)
Bac.physeq.prune.rarefy
```

```{r}
Bac.physeq.prune.rarefy = subset_taxa(Bac.physeq.prune.rarefy, Kingdom != "Rhizaria")
Bac.physeq.prune.rarefy = subset_taxa(Bac.physeq.prune.rarefy, Kingdom != "Chromista")
Bac.physeq.prune.rarefy = subset_taxa(Bac.physeq.prune.rarefy, Kingdom != "Unassigned")
Bac.physeq.prune.rarefy = subset_taxa(Bac.physeq.prune.rarefy, Kingdom != "D_0__Eukaryota")
Bac.physeq.prune.rarefy
```

```{r}
Bac.physeq.prune.rarefy.SF = subset_samples(Bac.physeq.prune.rarefy, Layer=="Surface")
```

```{r}
Bac.physeq.prune.rarefy.SUB = subset_samples(Bac.physeq.prune.rarefy, Layer=="Subsurface")
```

####Fungi
```{r}
Fun.otus <- read.table("MC2018.network.FG.otu_table.csv",header=T,sep=",",row.names=1)
Fun.otumat <- as(as.matrix(Fun.otus), "matrix")
Fun.OTU = otu_table(Fun.otumat, taxa_are_rows = TRUE)
```

```{r}
Fun.taxmat <- read.table("FG.network.taxonomy.csv", header=T,sep=",",row.names=1)
Fun.taxmat <- as(as.matrix(Fun.taxmat),"matrix")
Fun.TAX = tax_table(Fun.taxmat)
```

```{r warning=FALSE}
Fun.physeq = phyloseq(Fun.OTU,Fun.TAX,sampleData)
```

```{r }
Fun.physeq.prune = prune_taxa(taxa_sums(Fun.physeq) > 1, Fun.physeq)
```

```{r warning=FALSE}
set.seed(1)
Fun.physeq.prune.rarefy = rarefy_even_depth(Fun.physeq.prune, sample.size = 6842, replace = FALSE, trimOTUs = FALSE)
Fun.physeq.prune.rarefy
```

```{r}
Fun.physeq.prune.rarefy = subset_taxa(Fun.physeq.prune.rarefy, Kingdom != "Rhizaria")
Fun.physeq.prune.rarefy = subset_taxa(Fun.physeq.prune.rarefy, Kingdom != "Chromista")
Fun.physeq.prune.rarefy = subset_taxa(Fun.physeq.prune.rarefy, Kingdom != "Unassigned")
Fun.physeq.prune.rarefy = subset_taxa(Fun.physeq.prune.rarefy, Kingdom != "D_0__Eukaryota")
Fun.physeq.prune.rarefy = subset_taxa(Fun.physeq.prune.rarefy, Kingdom != "NA")
Fun.physeq.prune.rarefy
```

```{r}
Fun.physeq.prune.rarefy.SF = subset_samples(Fun.physeq.prune.rarefy, Layer=="Surface")
```

```{r}
Fun.physeq.prune.rarefy.SUB = subset_samples(Fun.physeq.prune.rarefy, Layer=="Subsurface")
```



###SpiecEasi Cross Domain

```{r}
#Bac.physeq.prune.rarefy.SF.top100 = prune_taxa(names(sort(taxa_sums(Bac.physeq.prune.rarefy.SF), TRUE))[1:100], Bac.physeq.prune.rarefy.SF)
```

```{r}
#Fun.physeq.prune.rarefy.SF.top100 = prune_taxa(names(sort(taxa_sums(Fun.physeq.prune.rarefy.SF), TRUE))[1:300], Fun.physeq.prune.rarefy.SF)
```

```{r}
#pargs <- list(rep.num = 50, seed = 10010, ncores = 6)
#FG.Bac.network <- spiec.easi(list(Bac.physeq.prune.rarefy.SF.top100, Fun.physeq.prune.rarefy.SF.top100), method='glasso', nlambda=40,
#              lambda.min.ratio=1e-2, pulsar.params = pargs)
```

```{r}
#FG.BAC.top100.merged = merge_phyloseq(Bac.physeq.prune.rarefy.SF.top100, Fun.physeq.prune.rarefy.SF.top100)
#FG.BAC.top100.merged
```

```{r}
#easi.fun.bac.net <- adj2igraph(getRefit(FG.Bac.network), rmEmptyNodes=TRUE, vertex.attr=list(name=taxa_names(FG.BAC.top100.merged)))
```

```{r}
#net.df = as_long_data_frame(easi.fun.bac.net)
```

```{r}
#cdf = data.frame(OTU1 = net.df$`ver[el[, 1], ]`, OTU2 = net.df$`ver2[el[, 2], ]`, WEIGHT = as.vector(net.df$weight), stringsAsFactors = TRUE )
#cdf
```


```{r}
#write.csv(cdf, file="EasiFunBacNet.csv")
```


###Load rda for plot

```{r}
#Bac.physeq.prune.rarefy.LAC.SF = subset_samples(Bac.physeq.prune.rarefy, Crust_type=="LAC")
Bac.physeq.prune.rarefy.SUB.top200 = prune_taxa(names(sort(taxa_sums(Bac.physeq.prune.rarefy.SUB), TRUE))[1:200], Bac.physeq.prune.rarefy.SUB)
```

```{r}
#Fun.physeq.prune.rarefy.LAC.SF = subset_samples(Fun.physeq.prune.rarefy, Crust_type=="LAC")
Fun.physeq.prune.rarefy.SUB.top200 = prune_taxa(names(sort(taxa_sums(Fun.physeq.prune.rarefy.SUB), TRUE))[1:200], Fun.physeq.prune.rarefy.SUB)
```

```{r}
FG.BAC.SUB.merged = merge_phyloseq(Bac.physeq.prune.rarefy.SUB.top200, Fun.physeq.prune.rarefy.SUB.top200)
```

```{r}
load(file = "easi.fun.bac.SUB.all.e2L40.net.rda")
```


```{r}
easi.fun.bac.SUB.net
```


```{r}
set.seed(12345)
psplotnet.phylum = plot_network(easi.fun.bac.SUB.net, FG.BAC.SUB.merged, type='taxa', color="Phylum", label = "Genus" ,shape = "Kingdom", hjust = 0.5)
```


```{r}
psplotnet.phylum + ggtitle("Mojave Biocrust Microbial Community Network Analysis (Surface)")
```


```{r}
pdf("Figures/DOE.label.Biocrust_Microbial_Community_Network_Analysis_Surface_top_200.phylum.pdf", width = 15, height = 10)
psplotnet.phylum + ggtitle("Mojave Biocrust Microbial Community Network Analysis (Surface)") + theme(plot.title = element_text(hjust = 0.5))
dev.off()
```


## HUB detection

```{r warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
```

```{r}
# Identify isolated nodes
bad.vs<-V(easi.fun.bac.SUB.net)[degree(easi.fun.bac.SUB.net) == 0] 
# Remove isolated nodes
net.grph<-delete.vertices(easi.fun.bac.SUB.net, bad.vs)
```

```{r}
# Hub detection
net.cn <- closeness(net.grph)
net.bn <- betweenness(net.grph) 
net.pr <- page_rank(net.grph)$vector 
net.hs <- hub_score(net.grph)$vector
net.dg <- degree(net.grph)

hubs <- data.frame(hub_score(net.grph)$vector); colnames(hubs) <- c("hubscore")
hubs$OTU <- rownames(hubs)
hubs$betweeness <- net.bn
hubs$pr <- net.pr
hubs$degree <- net.dg
hubs$closness <- net.cn

arrange(hubs, -hubscore)
```

```{r}
tax.interkingdom <- data.frame(tax_table(FG.BAC.SUB.merged))
tax.interkingdom$OTU <- rownames(tax.interkingdom)
```

```{r}
# getting the mean relative abundance of each OTU
interkingdom.Allegan.filtered.ra <- FG.BAC.SUB.merged %>%   
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt() %>%                                         # Melt to long format
  arrange(OTU)
mean.rel.abund <- interkingdom.Allegan.filtered.ra %>% 
  group_by(OTU) %>% 
  nest() %>%
  mutate(mean.relabund = purrr::map(data,~mean(.$Abundance*100))) %>%
  mutate(SE.relabund = purrr::map(data,~sd(.$Abundance*100)/sqrt(length(.$Abundance*100)))) %>%
  unnest(mean.relabund, SE.relabund)

nodes.stats <- hubs
nodes.stats$mean.abundance <- mean.rel.abund$mean.relabund[match(nodes.stats$OTU, mean.rel.abund$OTU)]
nodes.stats$Label <- match(nodes.stats$OTU, tax.interkingdom$OTU)
nodes.stats$Species <- interkingdom.Allegan.filtered.ra$Species[match(nodes.stats$OTU, interkingdom.Allegan.filtered.ra$OTU)]
nodes.stats$Genus <- interkingdom.Allegan.filtered.ra$Genus[match(nodes.stats$OTU, interkingdom.Allegan.filtered.ra$OTU)]
nodes.stats$Phylum <- interkingdom.Allegan.filtered.ra$Phylum[match(nodes.stats$OTU, interkingdom.Allegan.filtered.ra$OTU)]
nodes.stats$Kingdom <- interkingdom.Allegan.filtered.ra$Kingdom[match(nodes.stats$OTU, interkingdom.Allegan.filtered.ra$OTU)]

mean.close <- mean(log10(nodes.stats$closness))
sd.close <- sd(log10(nodes.stats$closness))
hubline.close <- (mean.close + 1.65*sd.close)

z.score.close = (hubline.close - mean.close)/sd.close
pnorm(z.score.close) # line is above 90 % - equal to p = 0.1

hist(log10(nodes.stats$degree))
mean.degree <- mean(log10(nodes.stats$degree))
sd.degree <- sd(log10(nodes.stats$degree))
hubline.degree <- (mean.degree + 1.65*sd.degree)

z.score.degree = (hubline.degree - mean.degree)/sd.degree
pnorm(z.score.degree) # line is above 90 % - equal to p = 0.1

mean.between <- mean(log10(nodes.stats$betweeness[nodes.stats$betweeness > 0]))
sd.between <- sd(log10(nodes.stats$betweeness[nodes.stats$betweeness > 0]))
hubline.between <- (mean.between + 1.65*sd.between)

z.score.between = (hubline.between - mean.between)/sd.between
pnorm(z.score.between) # line is above 90 % - equal to p = 0.1
```

```{r}
nodes.stats
```

```{r}
library(ggrepel)
#close <- ggplot() + 
#  geom_point(data = nodes.stats, aes(size = mean.abundance, x = closness, y = degree), alpha = 0.6) +
#  scale_size_continuous(name = "Relative Abundance") +
#  theme_bw() + 
#  geom_text_repel(data = subset(nodes.stats, closness > 10^hubline.close & degree > 10^hubline.degree), aes(x = closness, y = degree, label = Label)) +
#  xlab("Closeness Centrality") + 
#  ylab("Degree") + 
#  geom_vline(xintercept = 10^hubline.close, linetype = 2) + 
#  geom_hline(yintercept = 10^hubline.degree, linetype = 2)

#cbbPalette <- c("#999999", "#E69F00", "#0072B2", "#56B4E9", "#F0E442", "#D55E00", "#CC79A7", "#009E73", "midnightblue", "lightgreen", "aquamarine4","lavenderblush2","brown", "snow3", "black")

#cbbPalette <- c("#E69F00", "#999999", "#0072B2", "#56B4E9", "#F0E442", "lavenderblush2", "#CC79A7", "#009E73", "midnightblue", "lightgreen", "aquamarine4","#D55E00","brown", "snow3", "black", "mediumpurple1", "mistyrose1", "maroon1", "turquoise")

cbbPalette <- c("#E69F00", "#999999", "#0072B2", "#56B4E9", "#F0E442", "#CC79A7", "#009E73","lavenderblush2", "midnightblue", "lightgreen", "turquoise","aquamarine4","mediumpurple1", "mistyrose1", "maroon1", "#D55E00","brown", "snow3", "black")

between <- ggplot() + 
  geom_point(data = nodes.stats, aes(size = 0.8, y = betweeness, x = degree, color = Phylum, shape = Kingdom), alpha = 0.9) +
  theme_bw() + 
  scale_color_manual(values = cbbPalette) +
  geom_text_repel(data = subset(nodes.stats, betweeness > 4^hubline.between & degree > 4^hubline.degree), aes(y = betweeness, x = degree, label = Genus)) +
  ylab("Betweeness Centrality") + 
  xlab("Node Degree")
   #+
  #geom_hline(yintercept = 10^hubline.between, linetype = 2) + 
  #geom_vline(xintercept = 10^hubline.degree, linetype = 2)
```

```{r}
library(scales)
```

```{r}
between + 
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) + 
  annotation_logticks(sides="l")
```

```{r}
pdf("./New_Network/SUB_betweenness_noLabel.pdf", width = 8, height = 5)
between + 
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x))) + 
  annotation_logticks(sides="l")
dev.off()
```

#Node stats - import this first.
```{r }
write.csv(nodes.stats, "MojaveFungi_node_stats.csv")
```

Open a cytoscape network
```{r}
library(RCy3)
```

```{r }
createNetworkFromIgraph(net.grph,"MojaveFungi_net")
```

























